### ISSUE TITLE
please get rid of liburing private copy

### ISSUE THREAD

**Issue by lano1106** [frevib/io_uring-echo-server#10]
$ ./io_uring_echo_server 1976
io_uring echo server listening for connections on port: 1976
from io_uring_echo-server main() sizeof(struct io_uring): 160
From io_uring_queue_mmap() sizeof(*ring): 216 sizeof(struct io_uring): 216
Before memset() in io_uring_queue_mmap(): p->sq_entries: 2048
After memset() in io_uring_queue_mmap(): p->sq_entries: 0
io_uring_init_failed...
: Invalid argument

**Comment by frevib** [comment]
Done, thanks.
