### ISSUE TITLE
io_uring_echo_server becomes unresponsive in an uninterruptible sleep state

### ISSUE THREAD

**Issue by npuichigo** [frevib/io_uring-echo-server#13]
I faced the same issue during long running of the io_uring based server. Have u ever addressed this issue or have some insights about it?

**Comment by frevib** [comment]
Could you refer the to the other same issue?

**Comment by npuichigo** [comment]
[Here](https://github.com/facebookexperimental/libunifex/issues/315) I use io_uring together with c++ coroutines to write [a simple tcp server](https://github.com/npuichigo/crpc). After running for a long time, the [io_uring_enter](https://github.com/npuichigo/libunifex/blob/45a40f96eba3179c3d33783b4c07d96a728d33ea/source/linux/io_uring_context.cpp#L431) is hang and has no response to any new request. I use `top` to check the process and it's just sleeping.

**Comment by frevib** [comment]
No, I haven’t run into this issue. But I also haven’t been involveld in io_uring anymore for quite some time.

This seems like an issue with io_uring itself. I suggest asking it 

on the ML: https://lore.kernel.org/io-uring/
Jens on Twitter: @axboe

**Comment by npuichigo** [comment]
Thanks for your reply. I saw your extra information [here](https://github.com/frevib/io_uring-echo-server/blob/io-uring-feat-fast-poll/benchmarks/benchmarks.md) so I think you may have ran into the same issue.

**Comment by ericniebler** [comment]
Yuchao, can you comment on why you closed this?

**Comment by npuichigo** [comment]
Hi @ericniebler, I replied in libunifex [here](https://github.com/facebookexperimental/libunifex/issues/315#issuecomment-890283642) and I think it's not a bug of io_uring.
