### ISSUE TITLE
crashed when the number of clients exceeded 1100

### ISSUE THREAD

**Issue by alvinonmars** [frevib/io_uring-echo-server#17]
I tried many times，it crashed every time when the number of clients exceeded 1100.

cargo run --release -- --address 10.18.4.6:12346 --number 1500 --duration 60 --length 500

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/24663664/163685983-e3042b4b-1b57-4699-9fcd-4b490548c9d6.png">

**Comment by alvinonmars** [comment]
aws cx.4large. 16 core 32GB
<img width="390" alt="image" src="https://user-images.githubusercontent.com/24663664/163687097-87d783f6-224c-4f8f-9075-f7a01a0a8672.png">

**Comment by frevib** [comment]
Hi, this is only a bare minimum show case for io_uring. So please don't expect production-grade stability.
