### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by YangJingyuan99** [frevib/io_uring-echo-server#21]
Hi, I'm new to io_uring and I'm recently practicing using io_uring and using your code as a reference. I tried to modify the conn_info structure but found that the program was giving me errors, and it took me a long time to figure out that user_data only holds 64-bit data. I think your code may be misleading to people new to io_uring, although your conn_info structure happens to be 64-bit, but if you can, I suggest you store a pointer to conn_info in user_data, because the above problem really bothered me for two days :(

**Comment by frevib** [comment]
Hi, I’m sorry it bothered you. But this code is more like an as-is and I won’t do any changes to it unless they are bugs. I hope you can figure it or else ask our friend ChatGPT.
