### ISSUE TITLE
从源码上看两个比较模型不合理

### ISSUE THREAD

**Issue by nbuxrr** [frevib/io_uring-echo-server#9]
epoll-echo-server 单线程，高并发时，recv、send操作都是串行执行
uring-echo-server 单线程，高并发时，uring_read、uring_write的sqe在内核中是iou-wrk线程池并发执行

**Comment by frevib** [comment]
你有什么建议?

**Comment by liangyongrui** [comment]
都跑在单核上，是不是能说明问题？

> 你有什么建议?
